/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponseDto } from '../../models/category-response-dto';

export interface GetCategoryById$Params {
  'category-id': number;
}

export function getCategoryById(http: HttpClient, rootUrl: string, params: GetCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getCategoryById.PATH, 'get');
  if (params) {
    rb.path('category-id', params['category-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryResponseDto>;
    })
  );
}

getCategoryById.PATH = '/categories/{category-id}';
