/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateIconRequestDto } from '../../models/update-icon-request-dto';

export interface PatchCategoryIconById$Params {
  'category-id': number;
      body: UpdateIconRequestDto
}

export function patchCategoryIconById(http: HttpClient, rootUrl: string, params: PatchCategoryIconById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, patchCategoryIconById.PATH, 'patch');
  if (params) {
    rb.path('category-id', params['category-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

patchCategoryIconById.PATH = '/categories/{category-id}';
