/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CheckoutResponseDto } from '../../models/checkout-response-dto';

export interface HostedCheckout$Params {
  'cart-id': number;
}

export function hostedCheckout(http: HttpClient, rootUrl: string, params: HostedCheckout$Params, context?: HttpContext): Observable<StrictHttpResponse<CheckoutResponseDto>> {
  const rb = new RequestBuilder(rootUrl, hostedCheckout.PATH, 'post');
  if (params) {
    rb.path('cart-id', params['cart-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CheckoutResponseDto>;
    })
  );
}

hostedCheckout.PATH = '/payments/{cart-id}/checkout/hosted';
