/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addItem } from '../fn/cart-controller/add-item';
import { AddItem$Params } from '../fn/cart-controller/add-item';
import { CartResponseDto } from '../models/cart-response-dto';
import { createCart } from '../fn/cart-controller/create-cart';
import { CreateCart$Params } from '../fn/cart-controller/create-cart';
import { deleteCartById } from '../fn/cart-controller/delete-cart-by-id';
import { DeleteCartById$Params } from '../fn/cart-controller/delete-cart-by-id';
import { deleteItemById } from '../fn/cart-controller/delete-item-by-id';
import { DeleteItemById$Params } from '../fn/cart-controller/delete-item-by-id';
import { getCartById } from '../fn/cart-controller/get-cart-by-id';
import { GetCartById$Params } from '../fn/cart-controller/get-cart-by-id';
import { getCarts } from '../fn/cart-controller/get-carts';
import { GetCarts$Params } from '../fn/cart-controller/get-carts';
import { getItemById } from '../fn/cart-controller/get-item-by-id';
import { GetItemById$Params } from '../fn/cart-controller/get-item-by-id';
import { ItemResponseDto } from '../models/item-response-dto';
import { patchItemQuantityById } from '../fn/cart-controller/patch-item-quantity-by-id';
import { PatchItemQuantityById$Params } from '../fn/cart-controller/patch-item-quantity-by-id';

@Injectable({ providedIn: 'root' })
export class CartControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCarts()` */
  static readonly GetCartsPath = '/carts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCarts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCarts$Response(params?: GetCarts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CartResponseDto>>> {
    return getCarts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCarts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCarts(params?: GetCarts$Params, context?: HttpContext): Observable<Array<CartResponseDto>> {
    return this.getCarts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CartResponseDto>>): Array<CartResponseDto> => r.body)
    );
  }

  /** Path part for operation `createCart()` */
  static readonly CreateCartPath = '/carts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  createCart$Response(params?: CreateCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
    return createCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createCart(params?: CreateCart$Params, context?: HttpContext): Observable<CartResponseDto> {
    return this.createCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body)
    );
  }

  /** Path part for operation `addItem()` */
  static readonly AddItemPath = '/carts/{cart-id}/items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem$Response(params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponseDto>> {
    return addItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem(params: AddItem$Params, context?: HttpContext): Observable<ItemResponseDto> {
    return this.addItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ItemResponseDto>): ItemResponseDto => r.body)
    );
  }

  /** Path part for operation `patchItemQuantityById()` */
  static readonly PatchItemQuantityByIdPath = '/carts/{cart-id}/items/{item-id}/quantity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `patchItemQuantityById()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchItemQuantityById$Response(params: PatchItemQuantityById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return patchItemQuantityById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `patchItemQuantityById$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchItemQuantityById(params: PatchItemQuantityById$Params, context?: HttpContext): Observable<void> {
    return this.patchItemQuantityById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getCartById()` */
  static readonly GetCartByIdPath = '/carts/{cart-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCartById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartById$Response(params: GetCartById$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
    return getCartById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCartById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartById(params: GetCartById$Params, context?: HttpContext): Observable<CartResponseDto> {
    return this.getCartById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteCartById()` */
  static readonly DeleteCartByIdPath = '/carts/{cart-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCartById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCartById$Response(params: DeleteCartById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCartById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCartById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCartById(params: DeleteCartById$Params, context?: HttpContext): Observable<void> {
    return this.deleteCartById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getItemById()` */
  static readonly GetItemByIdPath = '/carts/{cart-id}/items/{item-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getItemById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItemById$Response(params: GetItemById$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponseDto>> {
    return getItemById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getItemById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItemById(params: GetItemById$Params, context?: HttpContext): Observable<ItemResponseDto> {
    return this.getItemById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ItemResponseDto>): ItemResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteItemById()` */
  static readonly DeleteItemByIdPath = '/carts/{cart-id}/items/{item-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteItemById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItemById$Response(params: DeleteItemById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteItemById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteItemById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItemById(params: DeleteItemById$Params, context?: HttpContext): Observable<void> {
    return this.deleteItemById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
