/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoryResponseDto } from '../models/category-response-dto';
import { createCategory } from '../fn/category-controller/create-category';
import { CreateCategory$Params } from '../fn/category-controller/create-category';
import { deleteCategoryById } from '../fn/category-controller/delete-category-by-id';
import { DeleteCategoryById$Params } from '../fn/category-controller/delete-category-by-id';
import { getCategoryById } from '../fn/category-controller/get-category-by-id';
import { GetCategoryById$Params } from '../fn/category-controller/get-category-by-id';
import { getRootCategory } from '../fn/category-controller/get-root-category';
import { GetRootCategory$Params } from '../fn/category-controller/get-root-category';
import { patchCategoryIconById } from '../fn/category-controller/patch-category-icon-by-id';
import { PatchCategoryIconById$Params } from '../fn/category-controller/patch-category-icon-by-id';

@Injectable({ providedIn: 'root' })
export class CategoryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRootCategory()` */
  static readonly GetRootCategoryPath = '/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRootCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRootCategory$Response(params?: GetRootCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponseDto>> {
    return getRootCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRootCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRootCategory(params?: GetRootCategory$Params, context?: HttpContext): Observable<CategoryResponseDto> {
    return this.getRootCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponseDto>): CategoryResponseDto => r.body)
    );
  }

  /** Path part for operation `createCategory()` */
  static readonly CreateCategoryPath = '/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory$Response(params: CreateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponseDto>> {
    return createCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory(params: CreateCategory$Params, context?: HttpContext): Observable<CategoryResponseDto> {
    return this.createCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponseDto>): CategoryResponseDto => r.body)
    );
  }

  /** Path part for operation `getCategoryById()` */
  static readonly GetCategoryByIdPath = '/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById$Response(params: GetCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponseDto>> {
    return getCategoryById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryById(params: GetCategoryById$Params, context?: HttpContext): Observable<CategoryResponseDto> {
    return this.getCategoryById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponseDto>): CategoryResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteCategoryById()` */
  static readonly DeleteCategoryByIdPath = '/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategoryById$Response(params: DeleteCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCategoryById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategoryById(params: DeleteCategoryById$Params, context?: HttpContext): Observable<void> {
    return this.deleteCategoryById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `patchCategoryIconById()` */
  static readonly PatchCategoryIconByIdPath = '/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `patchCategoryIconById()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchCategoryIconById$Response(params: PatchCategoryIconById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return patchCategoryIconById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `patchCategoryIconById$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchCategoryIconById(params: PatchCategoryIconById$Params, context?: HttpContext): Observable<void> {
    return this.patchCategoryIconById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
