/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoryTemplateResponseDto } from '../models/category-template-response-dto';
import { createCategoryTemplate } from '../fn/category-template-controller/create-category-template';
import { CreateCategoryTemplate$Params } from '../fn/category-template-controller/create-category-template';
import { deleteCategoryTemplateByCategoryId } from '../fn/category-template-controller/delete-category-template-by-category-id';
import { DeleteCategoryTemplateByCategoryId$Params } from '../fn/category-template-controller/delete-category-template-by-category-id';
import { getCategoryTemplateByCategoryId } from '../fn/category-template-controller/get-category-template-by-category-id';
import { GetCategoryTemplateByCategoryId$Params } from '../fn/category-template-controller/get-category-template-by-category-id';
import { getCategoryTemplateById } from '../fn/category-template-controller/get-category-template-by-id';
import { GetCategoryTemplateById$Params } from '../fn/category-template-controller/get-category-template-by-id';
import { getCategoryTemplates } from '../fn/category-template-controller/get-category-templates';
import { GetCategoryTemplates$Params } from '../fn/category-template-controller/get-category-templates';

@Injectable({ providedIn: 'root' })
export class CategoryTemplateControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCategoryTemplates()` */
  static readonly GetCategoryTemplatesPath = '/category-templates';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryTemplates()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplates$Response(params?: GetCategoryTemplates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryTemplateResponseDto>>> {
    return getCategoryTemplates(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryTemplates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplates(params?: GetCategoryTemplates$Params, context?: HttpContext): Observable<Array<CategoryTemplateResponseDto>> {
    return this.getCategoryTemplates$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CategoryTemplateResponseDto>>): Array<CategoryTemplateResponseDto> => r.body)
    );
  }

  /** Path part for operation `createCategoryTemplate()` */
  static readonly CreateCategoryTemplatePath = '/category-templates';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCategoryTemplate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategoryTemplate$Response(params: CreateCategoryTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryTemplateResponseDto>> {
    return createCategoryTemplate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCategoryTemplate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategoryTemplate(params: CreateCategoryTemplate$Params, context?: HttpContext): Observable<CategoryTemplateResponseDto> {
    return this.createCategoryTemplate$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryTemplateResponseDto>): CategoryTemplateResponseDto => r.body)
    );
  }

  /** Path part for operation `getCategoryTemplateById()` */
  static readonly GetCategoryTemplateByIdPath = '/category-templates/{category-template-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryTemplateById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplateById$Response(params: GetCategoryTemplateById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryTemplateResponseDto>> {
    return getCategoryTemplateById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryTemplateById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplateById(params: GetCategoryTemplateById$Params, context?: HttpContext): Observable<CategoryTemplateResponseDto> {
    return this.getCategoryTemplateById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryTemplateResponseDto>): CategoryTemplateResponseDto => r.body)
    );
  }

  /** Path part for operation `getCategoryTemplateByCategoryId()` */
  static readonly GetCategoryTemplateByCategoryIdPath = '/category-templates/category/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCategoryTemplateByCategoryId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplateByCategoryId$Response(params: GetCategoryTemplateByCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryTemplateResponseDto>> {
    return getCategoryTemplateByCategoryId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCategoryTemplateByCategoryId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCategoryTemplateByCategoryId(params: GetCategoryTemplateByCategoryId$Params, context?: HttpContext): Observable<CategoryTemplateResponseDto> {
    return this.getCategoryTemplateByCategoryId$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryTemplateResponseDto>): CategoryTemplateResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteCategoryTemplateByCategoryId()` */
  static readonly DeleteCategoryTemplateByCategoryIdPath = '/category-templates/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCategoryTemplateByCategoryId()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategoryTemplateByCategoryId$Response(params: DeleteCategoryTemplateByCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCategoryTemplateByCategoryId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCategoryTemplateByCategoryId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategoryTemplateByCategoryId(params: DeleteCategoryTemplateByCategoryId$Params, context?: HttpContext): Observable<void> {
    return this.deleteCategoryTemplateByCategoryId$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
