/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createFeedback } from '../fn/feedback-controller/create-feedback';
import { CreateFeedback$Params } from '../fn/feedback-controller/create-feedback';
import { FeedbackResponseDto } from '../models/feedback-response-dto';
import { getFeedbacksByCartId } from '../fn/feedback-controller/get-feedbacks-by-cart-id';
import { GetFeedbacksByCartId$Params } from '../fn/feedback-controller/get-feedbacks-by-cart-id';
import { getFeedbacksByProductId } from '../fn/feedback-controller/get-feedbacks-by-product-id';
import { GetFeedbacksByProductId$Params } from '../fn/feedback-controller/get-feedbacks-by-product-id';
import { getPendingFeedbacksByCartId } from '../fn/feedback-controller/get-pending-feedbacks-by-cart-id';
import { GetPendingFeedbacksByCartId$Params } from '../fn/feedback-controller/get-pending-feedbacks-by-cart-id';
import { PageResponseFeedbackResponseDto } from '../models/page-response-feedback-response-dto';

@Injectable({ providedIn: 'root' })
export class FeedbackControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getFeedbacksByProductId()` */
  static readonly GetFeedbacksByProductIdPath = '/feedbacks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeedbacksByProductId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByProductId$Response(params: GetFeedbacksByProductId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseFeedbackResponseDto>> {
    return getFeedbacksByProductId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeedbacksByProductId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByProductId(params: GetFeedbacksByProductId$Params, context?: HttpContext): Observable<PageResponseFeedbackResponseDto> {
    return this.getFeedbacksByProductId$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseFeedbackResponseDto>): PageResponseFeedbackResponseDto => r.body)
    );
  }

  /** Path part for operation `createFeedback()` */
  static readonly CreateFeedbackPath = '/feedbacks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFeedback$Response(params: CreateFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<FeedbackResponseDto>> {
    return createFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFeedback(params: CreateFeedback$Params, context?: HttpContext): Observable<FeedbackResponseDto> {
    return this.createFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<FeedbackResponseDto>): FeedbackResponseDto => r.body)
    );
  }

  /** Path part for operation `getPendingFeedbacksByCartId()` */
  static readonly GetPendingFeedbacksByCartIdPath = '/feedbacks/pending/{cart-id}/cart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPendingFeedbacksByCartId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingFeedbacksByCartId$Response(params: GetPendingFeedbacksByCartId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<number>>> {
    return getPendingFeedbacksByCartId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPendingFeedbacksByCartId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPendingFeedbacksByCartId(params: GetPendingFeedbacksByCartId$Params, context?: HttpContext): Observable<Array<number>> {
    return this.getPendingFeedbacksByCartId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<number>>): Array<number> => r.body)
    );
  }

  /** Path part for operation `getFeedbacksByCartId()` */
  static readonly GetFeedbacksByCartIdPath = '/feedbacks/commited/{cart-id}/cart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeedbacksByCartId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByCartId$Response(params: GetFeedbacksByCartId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FeedbackResponseDto>>> {
    return getFeedbacksByCartId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeedbacksByCartId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByCartId(params: GetFeedbacksByCartId$Params, context?: HttpContext): Observable<Array<FeedbackResponseDto>> {
    return this.getFeedbacksByCartId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FeedbackResponseDto>>): Array<FeedbackResponseDto> => r.body)
    );
  }

}
