/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CheckoutResponseDto } from '../models/checkout-response-dto';
import { hostedCheckout } from '../fn/payment-controller/hosted-checkout';
import { HostedCheckout$Params } from '../fn/payment-controller/hosted-checkout';

@Injectable({ providedIn: 'root' })
export class PaymentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `hostedCheckout()` */
  static readonly HostedCheckoutPath = '/payments/{cart-id}/checkout/hosted';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hostedCheckout()` instead.
   *
   * This method doesn't expect any request body.
   */
  hostedCheckout$Response(params: HostedCheckout$Params, context?: HttpContext): Observable<StrictHttpResponse<CheckoutResponseDto>> {
    return hostedCheckout(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hostedCheckout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hostedCheckout(params: HostedCheckout$Params, context?: HttpContext): Observable<CheckoutResponseDto> {
    return this.hostedCheckout$Response(params, context).pipe(
      map((r: StrictHttpResponse<CheckoutResponseDto>): CheckoutResponseDto => r.body)
    );
  }

}
