/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProduct } from '../fn/product-controller/create-product';
import { CreateProduct$Params } from '../fn/product-controller/create-product';
import { createProductVariant } from '../fn/product-controller/create-product-variant';
import { CreateProductVariant$Params } from '../fn/product-controller/create-product-variant';
import { deleteProductById } from '../fn/product-controller/delete-product-by-id';
import { DeleteProductById$Params } from '../fn/product-controller/delete-product-by-id';
import { deleteProductVariantById } from '../fn/product-controller/delete-product-variant-by-id';
import { DeleteProductVariantById$Params } from '../fn/product-controller/delete-product-variant-by-id';
import { deleteProductVariantImageById } from '../fn/product-controller/delete-product-variant-image-by-id';
import { DeleteProductVariantImageById$Params } from '../fn/product-controller/delete-product-variant-image-by-id';
import { getFilteredProducts } from '../fn/product-controller/get-filtered-products';
import { GetFilteredProducts$Params } from '../fn/product-controller/get-filtered-products';
import { getProductById } from '../fn/product-controller/get-product-by-id';
import { GetProductById$Params } from '../fn/product-controller/get-product-by-id';
import { getProductsByCategoryId } from '../fn/product-controller/get-products-by-category-id';
import { GetProductsByCategoryId$Params } from '../fn/product-controller/get-products-by-category-id';
import { getProductsByOwner } from '../fn/product-controller/get-products-by-owner';
import { GetProductsByOwner$Params } from '../fn/product-controller/get-products-by-owner';
import { getProductVariantById } from '../fn/product-controller/get-product-variant-by-id';
import { GetProductVariantById$Params } from '../fn/product-controller/get-product-variant-by-id';
import { PageResponseProductResponseDto } from '../models/page-response-product-response-dto';
import { patchProductVariantPriceById } from '../fn/product-controller/patch-product-variant-price-by-id';
import { PatchProductVariantPriceById$Params } from '../fn/product-controller/patch-product-variant-price-by-id';
import { patchProductVariantQuantityById } from '../fn/product-controller/patch-product-variant-quantity-by-id';
import { PatchProductVariantQuantityById$Params } from '../fn/product-controller/patch-product-variant-quantity-by-id';
import { ProductResponseDto } from '../models/product-response-dto';
import { ProductVariantResponseDto } from '../models/product-variant-response-dto';
import { uploadProductVariantImage } from '../fn/product-controller/upload-product-variant-image';
import { UploadProductVariantImage$Params } from '../fn/product-controller/upload-product-variant-image';

@Injectable({ providedIn: 'root' })
export class ProductControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProductsByCategoryId()` */
  static readonly GetProductsByCategoryIdPath = '/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductsByCategoryId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCategoryId$Response(params: GetProductsByCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponseDto>> {
    return getProductsByCategoryId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductsByCategoryId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByCategoryId(params: GetProductsByCategoryId$Params, context?: HttpContext): Observable<PageResponseProductResponseDto> {
    return this.getProductsByCategoryId$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductResponseDto>): PageResponseProductResponseDto => r.body)
    );
  }

  /** Path part for operation `createProduct()` */
  static readonly CreateProductPath = '/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProduct()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct$Response(params: CreateProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponseDto>> {
    return createProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProduct$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct(params: CreateProduct$Params, context?: HttpContext): Observable<ProductResponseDto> {
    return this.createProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponseDto>): ProductResponseDto => r.body)
    );
  }

  /** Path part for operation `createProductVariant()` */
  static readonly CreateProductVariantPath = '/products/{product-id}/product-variants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProductVariant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductVariant$Response(params: CreateProductVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductVariantResponseDto>> {
    return createProductVariant(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProductVariant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProductVariant(params: CreateProductVariant$Params, context?: HttpContext): Observable<ProductVariantResponseDto> {
    return this.createProductVariant$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductVariantResponseDto>): ProductVariantResponseDto => r.body)
    );
  }

  /** Path part for operation `uploadProductVariantImage()` */
  static readonly UploadProductVariantImagePath = '/products/{product-id}/product-variants/{product-variant-id}/image';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadProductVariantImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductVariantImage$Response(params: UploadProductVariantImage$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductVariantResponseDto>> {
    return uploadProductVariantImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadProductVariantImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProductVariantImage(params: UploadProductVariantImage$Params, context?: HttpContext): Observable<ProductVariantResponseDto> {
    return this.uploadProductVariantImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductVariantResponseDto>): ProductVariantResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteProductVariantImageById()` */
  static readonly DeleteProductVariantImageByIdPath = '/products/{product-id}/product-variants/{product-variant-id}/image';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProductVariantImageById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductVariantImageById$Response(params: DeleteProductVariantImageById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProductVariantImageById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProductVariantImageById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductVariantImageById(params: DeleteProductVariantImageById$Params, context?: HttpContext): Observable<void> {
    return this.deleteProductVariantImageById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getFilteredProducts()` */
  static readonly GetFilteredProductsPath = '/products/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFilteredProducts()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getFilteredProducts$Response(params: GetFilteredProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponseDto>> {
    return getFilteredProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFilteredProducts$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getFilteredProducts(params: GetFilteredProducts$Params, context?: HttpContext): Observable<PageResponseProductResponseDto> {
    return this.getFilteredProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseProductResponseDto>): PageResponseProductResponseDto => r.body)
    );
  }

  /** Path part for operation `patchProductVariantQuantityById()` */
  static readonly PatchProductVariantQuantityByIdPath = '/products/{product-id}/product-variants/{product-variant-id}/quantity';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `patchProductVariantQuantityById()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchProductVariantQuantityById$Response(params: PatchProductVariantQuantityById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return patchProductVariantQuantityById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `patchProductVariantQuantityById$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchProductVariantQuantityById(params: PatchProductVariantQuantityById$Params, context?: HttpContext): Observable<void> {
    return this.patchProductVariantQuantityById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `patchProductVariantPriceById()` */
  static readonly PatchProductVariantPriceByIdPath = '/products/{product-id}/product-variants/{product-variant-id}/price';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `patchProductVariantPriceById()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchProductVariantPriceById$Response(params: PatchProductVariantPriceById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return patchProductVariantPriceById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `patchProductVariantPriceById$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  patchProductVariantPriceById(params: PatchProductVariantPriceById$Params, context?: HttpContext): Observable<void> {
    return this.patchProductVariantPriceById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProductById()` */
  static readonly GetProductByIdPath = '/products/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductById$Response(params: GetProductById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponseDto>> {
    return getProductById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductById(params: GetProductById$Params, context?: HttpContext): Observable<ProductResponseDto> {
    return this.getProductById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductResponseDto>): ProductResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteProductById()` */
  static readonly DeleteProductByIdPath = '/products/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProductById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductById$Response(params: DeleteProductById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProductById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProductById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductById(params: DeleteProductById$Params, context?: HttpContext): Observable<void> {
    return this.deleteProductById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProductVariantById()` */
  static readonly GetProductVariantByIdPath = '/products/{product-id}/product-variants/{product-variant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductVariantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductVariantById$Response(params: GetProductVariantById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductVariantResponseDto>> {
    return getProductVariantById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductVariantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductVariantById(params: GetProductVariantById$Params, context?: HttpContext): Observable<ProductVariantResponseDto> {
    return this.getProductVariantById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductVariantResponseDto>): ProductVariantResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteProductVariantById()` */
  static readonly DeleteProductVariantByIdPath = '/products/{product-id}/product-variants/{product-variant-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProductVariantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductVariantById$Response(params: DeleteProductVariantById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProductVariantById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProductVariantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProductVariantById(params: DeleteProductVariantById$Params, context?: HttpContext): Observable<void> {
    return this.deleteProductVariantById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProductsByOwner()` */
  static readonly GetProductsByOwnerPath = '/products/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductsByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByOwner$Response(params?: GetProductsByOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductResponseDto>>> {
    return getProductsByOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductsByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductsByOwner(params?: GetProductsByOwner$Params, context?: HttpContext): Observable<Array<ProductResponseDto>> {
    return this.getProductsByOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductResponseDto>>): Array<ProductResponseDto> => r.body)
    );
  }

}
