/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProperty } from '../fn/property-controller/create-property';
import { CreateProperty$Params } from '../fn/property-controller/create-property';
import { deletePropertyById } from '../fn/property-controller/delete-property-by-id';
import { DeletePropertyById$Params } from '../fn/property-controller/delete-property-by-id';
import { getProperties } from '../fn/property-controller/get-properties';
import { GetProperties$Params } from '../fn/property-controller/get-properties';
import { getPropertyById } from '../fn/property-controller/get-property-by-id';
import { GetPropertyById$Params } from '../fn/property-controller/get-property-by-id';
import { PropertyResponseDto } from '../models/property-response-dto';

@Injectable({ providedIn: 'root' })
export class PropertyControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getProperties()` */
  static readonly GetPropertiesPath = '/properties';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProperties()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProperties$Response(params?: GetProperties$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PropertyResponseDto>>> {
    return getProperties(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProperties$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProperties(params?: GetProperties$Params, context?: HttpContext): Observable<Array<PropertyResponseDto>> {
    return this.getProperties$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PropertyResponseDto>>): Array<PropertyResponseDto> => r.body)
    );
  }

  /** Path part for operation `createProperty()` */
  static readonly CreatePropertyPath = '/properties';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProperty()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProperty$Response(params: CreateProperty$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponseDto>> {
    return createProperty(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProperty$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProperty(params: CreateProperty$Params, context?: HttpContext): Observable<PropertyResponseDto> {
    return this.createProperty$Response(params, context).pipe(
      map((r: StrictHttpResponse<PropertyResponseDto>): PropertyResponseDto => r.body)
    );
  }

  /** Path part for operation `getPropertyById()` */
  static readonly GetPropertyByIdPath = '/properties/{property-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPropertyById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPropertyById$Response(params: GetPropertyById$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponseDto>> {
    return getPropertyById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPropertyById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPropertyById(params: GetPropertyById$Params, context?: HttpContext): Observable<PropertyResponseDto> {
    return this.getPropertyById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PropertyResponseDto>): PropertyResponseDto => r.body)
    );
  }

  /** Path part for operation `deletePropertyById()` */
  static readonly DeletePropertyByIdPath = '/properties/{property-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePropertyById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePropertyById$Response(params: DeletePropertyById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletePropertyById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePropertyById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePropertyById(params: DeletePropertyById$Params, context?: HttpContext): Observable<void> {
    return this.deletePropertyById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
