/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { handleStripeEvent } from '../fn/webhook-controller/handle-stripe-event';
import { HandleStripeEvent$Params } from '../fn/webhook-controller/handle-stripe-event';

@Injectable({ providedIn: 'root' })
export class WebhookControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `handleStripeEvent()` */
  static readonly HandleStripeEventPath = '/webhook';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `handleStripeEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  handleStripeEvent$Response(params: HandleStripeEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return handleStripeEvent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `handleStripeEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  handleStripeEvent(params: HandleStripeEvent$Params, context?: HttpContext): Observable<string> {
    return this.handleStripeEvent$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
