/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackRequestDto } from '../../models/feedback-request-dto';
import { FeedbackResponseDto } from '../../models/feedback-response-dto';

export interface CreateFeedback$Params {
      body: FeedbackRequestDto
}

export function createFeedback(http: HttpClient, rootUrl: string, params: CreateFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<FeedbackResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createFeedback.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FeedbackResponseDto>;
    })
  );
}

createFeedback.PATH = '/feedbacks';
