/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackResponseDto } from '../../models/feedback-response-dto';

export interface GetFeedbacksByCartId$Params {
  'cart-id': number;
}

export function getFeedbacksByCartId(http: HttpClient, rootUrl: string, params: GetFeedbacksByCartId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FeedbackResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getFeedbacksByCartId.PATH, 'get');
  if (params) {
    rb.path('cart-id', params['cart-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FeedbackResponseDto>>;
    })
  );
}

getFeedbacksByCartId.PATH = '/feedbacks/commited/{cart-id}/cart';
