/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseFeedbackResponseDto } from '../../models/page-response-feedback-response-dto';

export interface GetFeedbacksByProductId$Params {
  'page-number'?: number;
  'page-size'?: number;
  sort?: string;
  direction?: string;
  'product-id': number;
}

export function getFeedbacksByProductId(http: HttpClient, rootUrl: string, params: GetFeedbacksByProductId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseFeedbackResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getFeedbacksByProductId.PATH, 'get');
  if (params) {
    rb.query('page-number', params['page-number'], {});
    rb.query('page-size', params['page-size'], {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('product-id', params['product-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseFeedbackResponseDto>;
    })
  );
}

getFeedbacksByProductId.PATH = '/feedbacks';
