/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductVariantSnapshot } from '../models/product-variant-snapshot';
export interface ItemResponseDto {
  available?: boolean;
  id?: number;
  present?: boolean;
  productSnapshot?: ProductVariantSnapshot;
  quantity?: number;
  note?: number;
  comment?: string;
}
