/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {FormControl} from '@angular/forms';

export interface ProductDraftCache {
  name: string;
  categoryId: number | null;
  description: FormControl<string | null>;
}
