/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductVariantSnapshot {
  createdDate?: string;
  description?: string;
  imageUrl?: string;
  name?: string;
  price?: number;
  productId?: number;
  productVariantId?: number;
  properties?: {
[key: string]: string;
};
}
