/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {FilePreview} from './file-preview';

export interface VariantDraftCache {
  price: string;
  quantity: number | null;
  filePreview: FilePreview | null;
  properties: Record<number, string | null>;
}
