/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemRequestDto } from '../../models/item-request-dto';
import { ItemResponseDto } from '../../models/item-response-dto';

export interface AddItem$Params {
  'cart-id': number;
      body: ItemRequestDto
}

export function addItem(http: HttpClient, rootUrl: string, params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponseDto>> {
  const rb = new RequestBuilder(rootUrl, addItem.PATH, 'post');
  if (params) {
    rb.path('cart-id', params['cart-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemResponseDto>;
    })
  );
}

addItem.PATH = '/carts/{cart-id}/items';
