/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDto } from '../../models/cart-response-dto';

export interface CreateCart$Params {
}

export function createCart(http: HttpClient, rootUrl: string, params?: CreateCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createCart.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDto>;
    })
  );
}

createCart.PATH = '/carts';
