/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartResponseDto } from '../../models/cart-response-dto';

export interface GetCartById$Params {
  'cart-id': number;
}

export function getCartById(http: HttpClient, rootUrl: string, params: GetCartById$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getCartById.PATH, 'get');
  if (params) {
    rb.path('cart-id', params['cart-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartResponseDto>;
    })
  );
}

getCartById.PATH = '/carts/{cart-id}';
