/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryTemplateRequestDto } from '../../models/category-template-request-dto';
import { CategoryTemplateResponseDto } from '../../models/category-template-response-dto';

export interface CreateCategoryTemplate$Params {
      body: CategoryTemplateRequestDto
}

export function createCategoryTemplate(http: HttpClient, rootUrl: string, params: CreateCategoryTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryTemplateResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createCategoryTemplate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryTemplateResponseDto>;
    })
  );
}

createCategoryTemplate.PATH = '/category-templates';
