/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryTemplateResponseDto } from '../../models/category-template-response-dto';

export interface GetCategoryTemplateById$Params {
  'category-template-id': number;
}

export function getCategoryTemplateById(http: HttpClient, rootUrl: string, params: GetCategoryTemplateById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryTemplateResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getCategoryTemplateById.PATH, 'get');
  if (params) {
    rb.path('category-template-id', params['category-template-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryTemplateResponseDto>;
    })
  );
}

getCategoryTemplateById.PATH = '/category-templates/{category-template-id}';
