/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryTemplateResponseDto } from '../../models/category-template-response-dto';

export interface GetCategoryTemplates$Params {
}

export function getCategoryTemplates(http: HttpClient, rootUrl: string, params?: GetCategoryTemplates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryTemplateResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, getCategoryTemplates.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryTemplateResponseDto>>;
    })
  );
}

getCategoryTemplates.PATH = '/category-templates';
