package com.javuar.shop.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
public enum BusinessErrorCodes {
    // Category
    ROOT_CATEGORY_NOT_FOUND(NOT_FOUND),
    CATEGORY_NOT_FOUND(NOT_FOUND),
    DUPLICATE_CATEGORY_NAME(BAD_REQUEST),
    DUPLICATE_ROOT_CATEGORY(BAD_REQUEST),

    // Property
    DUPLICATE_PROPERTY_NAME(BAD_REQUEST),
    PROPERTY_NOT_FOUND(NOT_FOUND),

    // CategoryTemplate
    CATEGORY_TEMPLATE_NOT_FOUND(NOT_FOUND),
    DUPLICATE_CATEGORY_TEMPLATE(BAD_REQUEST),
    NON_LEAF_CATEGORY(BAD_REQUEST),

    // Product
    FAILED_TO_READ_FILE(BAD_REQUEST),
    FAILED_TO_REMOVE_FILE(INTERNAL_SERVER_ERROR),
    INVALID_PRODUCT_VARIANT_FORMAT(BAD_REQUEST),
    MISSING_FILE(BAD_REQUEST),
    PRODUCT_NOT_FOUND(NOT_FOUND),
    PRODUCT_VARIANT_NOT_FOUND(NOT_FOUND),
    UNAUTHORIZED_PRODUCT_ACTION(FORBIDDEN),

    // Cart
    CART_FINALIZED(BAD_REQUEST),
    CART_NOT_FOUND(NOT_FOUND),
    DUPLICATE_ITEM(BAD_REQUEST),
    ITEM_NOT_FOUND(NOT_FOUND),
    OUT_OF_STOCK(BAD_REQUEST),
    QUANTITY_UNCHANGED(BAD_REQUEST),
    SELF_PURCHASE_NOT_ALLOWED(BAD_REQUEST),
    UNAUTHORIZED_CART_ACTION(FORBIDDEN),

    // Feedback
    UNAUTHORIZED_FEEDBACK_ACTION(FORBIDDEN),

    // User
    USER_NOT_FOUND(INTERNAL_SERVER_ERROR),

    // Payment
    STRIPE_CUSTOMER_CREATION(INTERNAL_SERVER_ERROR),
    INVALID_STRIPE_SIGNATURE(BAD_REQUEST),
    STRIPE_SESSION_CREATION(INTERNAL_SERVER_ERROR),

    // Common
    VALIDATION_ERROR(BAD_REQUEST),
    DATA_INTEGRITY_VIOLATION(BAD_REQUEST),
    MISSING_REQUEST_PARAMETER(BAD_REQUEST),
    HTTP_MESSAGE_NOT_READABLE(BAD_REQUEST),
    ACCESS_DENIED(BAD_REQUEST);

    private final HttpStatus httpStatus;

    BusinessErrorCodes(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }
}