/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Inject, Injectable, PLATFORM_ID} from '@angular/core';
import {isPlatformBrowser} from '@angular/common';
import {ROOT_URL} from '../tokens';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  rootUrl: string = 'http://localhost:8080/api/v1'; // Fallback used only during local development

  constructor(
    @Inject(PLATFORM_ID) private _platformId: Object,
    @Inject(ROOT_URL) private _rootUrl: any
  ) {
    if (_rootUrl instanceof Error) {
      console.warn(_rootUrl.message);
      return;
    }

    const platform: 'Browser' | 'Server' = isPlatformBrowser(this._platformId) ? 'Browser' : 'Server';
    console.log(`${platform} rootUrl has been set to ${this._rootUrl}`);

    this.rootUrl = this._rootUrl;
  }
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
