/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';
import {IS_BROWSER} from '../common/constants/constants';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  rootUrl: string = 'http://localhost:8080/api/v1';

  constructor() {
    fetch('/assets/config.json')
      .then((res: Response): Promise<any> => res.json())
      .then((cfg: any): any => this.rootUrl = cfg.apiUrl);
  }
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
