/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { WebhookControllerService } from './services/webhook-controller.service';
import { PropertyControllerService } from './services/property-controller.service';
import { ProductControllerService } from './services/product-controller.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { FeedbackControllerService } from './services/feedback-controller.service';
import { CategoryTemplateControllerService } from './services/category-template-controller.service';
import { CategoryControllerService } from './services/category-controller.service';
import { CartControllerService } from './services/cart-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    WebhookControllerService,
    PropertyControllerService,
    ProductControllerService,
    PaymentControllerService,
    FeedbackControllerService,
    CategoryTemplateControllerService,
    CategoryControllerService,
    CartControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
