/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropertyResponseDto } from '../../models/property-response-dto';

export interface GetPropertyById$Params {
  'property-id': number;
}

export function getPropertyById(http: HttpClient, rootUrl: string, params: GetPropertyById$Params, context?: HttpContext): Observable<StrictHttpResponse<PropertyResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getPropertyById.PATH, 'get');
  if (params) {
    rb.path('property-id', params['property-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropertyResponseDto>;
    })
  );
}

getPropertyById.PATH = '/properties/{property-id}';
