/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductVariantRequestDto } from '../../models/product-variant-request-dto';
import { ProductVariantResponseDto } from '../../models/product-variant-response-dto';

export interface CreateProductVariant$Params {
  'product-id': number;
      body: ProductVariantRequestDto
}

export function createProductVariant(http: HttpClient, rootUrl: string, params: CreateProductVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductVariantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, createProductVariant.PATH, 'post');
  if (params) {
    rb.path('product-id', params['product-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductVariantResponseDto>;
    })
  );
}

createProductVariant.PATH = '/products/{product-id}/product-variants';
