/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteProductVariantImageById$Params {
  'product-id': number;
  'product-variant-id': number;
}

export function deleteProductVariantImageById(http: HttpClient, rootUrl: string, params: DeleteProductVariantImageById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteProductVariantImageById.PATH, 'delete');
  if (params) {
    rb.path('product-id', params['product-id'], {});
    rb.path('product-variant-id', params['product-variant-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteProductVariantImageById.PATH = '/products/{product-id}/product-variants/{product-variant-id}/image';
