/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseProductResponseDto } from '../../models/page-response-product-response-dto';

export interface GetFilteredProducts$Params {
  'page-number'?: number;
  'page-size'?: number;
  sort?: string;
  direction?: string;
  name?: string;
  quantity?: number;
  price?: number;
  'category-id': number;
      body: {
[key: string]: string;
}
}

export function getFilteredProducts(http: HttpClient, rootUrl: string, params: GetFilteredProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseProductResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getFilteredProducts.PATH, 'post');
  if (params) {
    rb.query('page-number', params['page-number'], {});
    rb.query('page-size', params['page-size'], {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('name', params.name, {});
    rb.query('quantity', params.quantity, {});
    rb.query('price', params.price, {});
    rb.query('category-id', params['category-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseProductResponseDto>;
    })
  );
}

getFilteredProducts.PATH = '/products/search';
