/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdatePriceRequestDto } from '../../models/update-price-request-dto';

export interface PatchProductVariantPriceById$Params {
  'product-id': number;
  'product-variant-id': number;
      body: UpdatePriceRequestDto
}

export function patchProductVariantPriceById(http: HttpClient, rootUrl: string, params: PatchProductVariantPriceById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, patchProductVariantPriceById.PATH, 'patch');
  if (params) {
    rb.path('product-id', params['product-id'], {});
    rb.path('product-variant-id', params['product-variant-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

patchProductVariantPriceById.PATH = '/products/{product-id}/product-variants/{product-variant-id}/price';
