/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductVariantResponseDto } from '../../models/product-variant-response-dto';

export interface UploadProductVariantImage$Params {
  'product-id': number;
  'product-variant-id': number;
      body?: {
'file': Blob;
}
}

export function uploadProductVariantImage(http: HttpClient, rootUrl: string, params: UploadProductVariantImage$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductVariantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, uploadProductVariantImage.PATH, 'post');
  if (params) {
    rb.path('product-id', params['product-id'], {});
    rb.path('product-variant-id', params['product-variant-id'], {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductVariantResponseDto>;
    })
  );
}

uploadProductVariantImage.PATH = '/products/{product-id}/product-variants/{product-variant-id}/image';
