/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemResponseDto } from '../models/item-response-dto';
export interface CartResponseDto {
  id?: number;
  isPaid?: boolean;
  items?: Array<ItemResponseDto>;
}
