/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponseDto {
  icon?: string;
  id?: number;
  name?: string;
  subcategories?: Array<CategoryResponseDto>;
  color?: string;
}
