/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyResponseDto } from '../models/property-response-dto';
export interface CategoryTemplateResponseDto {
  categoryId?: number;
  id?: number;
  properties?: Array<PropertyResponseDto>;
}
