/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeedbackResponseDto {
  comment?: string;
  id?: number;
  note?: number;
  productVariantId?: number;
}
