/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductVariantRequestDto {
  price: number;
  properties: {
[key: string]: string;
};
  quantity: number;
}
