/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductVariantResponseDto } from '../models/product-variant-response-dto';
export interface ProductResponseDto {
  categoryId?: number;
  description?: string;
  id?: number;
  name?: string;
  rate?: number;
  variants?: Array<ProductVariantResponseDto>;
}
