/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyPresetDto } from '../models/property-preset-dto';
export interface PropertyResponseDto {
  id?: number;
  name?: string;
  presets?: Array<PropertyPresetDto>;
  unit?: string;
  min?: number;
  max?: number;
  step?: number;
}
